# Nom du workflow
name: Talk Weather

# Déclenchement du workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "*/2 * * * *"  # Chaque 2 minutes

jobs:
  ask-weather:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Afficher l’heure d’exécution
        run: date

      - name: Obtenir la température
        run: |
          curl -s "https://wttr.in/Paris?format=%t&m" > temp.txt
          TEMP=$(cat temp.txt | tr -d '+') # exemple : "10°C"
          TEXT="Légère bruine et pluie, il fait $TEMP, prenez un parapluie."
          echo "$TEXT"
          echo "TEXT=$TEXT" >> $GITHUB_ENV

      - name: Convertir en parole avec ElevenLabs
        env:
          ELEVENLABS_API_KEY: ${{ secrets.ELEVENLABS_API_KEY }}
          TEXT: ${{ env.TEXT }}
        run: |
          echo "Texte à lire : $TEXT"
          VOICE_ID="AZnzlk1XvdvUeBnXmlld"  # Chloé

          # Créer un JSON valide avec jq
          echo '{}' | jq --arg txt "$TEXT" '{
            text: $txt,
            model_id: "eleven_multilingual_v1",
            voice_settings: {
              stability: 0.5,
              similarity_boost: 0.75
            }
          }' > payload.json

          # Envoyer la requête et récupérer l'audio
          curl -s -X POST https://api.elevenlabs.io/v1/text-to-speech/$VOICE_ID \
            -H "xi-api-key: $ELEVENLABS_API_KEY" \
            -H "Content-Type: application/json" \
            -d @payload.json --output weather.mp3

      - name: Télécharger l’audio
        uses: actions/upload-artifact@v4
        with:
          name: voix-meteo
          path: weather.mp3
