# Nom du workflow
name: Talk Weather

#Déclenchement du workflow
on:
  schedule:
    # Chaques 2 minutes
    - cron: "*/2 * * * *"

jobs: 
  # Nom du job
  ask-weatherr:
    # Nom de l'agent
    runs-on: ubuntu-latest
    # Les étapes du job
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get Weather
        run: 
          curl wttr.in/paris
          
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run script
        run: python talk_weather.py

