name: Talk Weather (Coqui TTS)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6,14 * * *"  # 8:00 i 16:00 czasu paryskiego

jobs:
  coqui-weather:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip ffmpeg
          pip install TTS

      - name: Get weather summary from Gemini
        env:
          GEMINI_API: ${{ secrets.GEMINI_API }}
        run: |
          set -e
          TEMP=$(curl -s "https://wttr.in/Paris?format=%C+%t&m")
          PROMPT="Résume la météo à Paris à partir de la réponse suivante : $TEMP, remplace tous les nombres par des mots, je ne veux ni chiffres ni nombres, je veux des lettres. La réponse doit uniquement contenir des informations sur la météo, accompagnées d'une recommandation adaptée à ce type de temps."

          PAYLOAD=$(jq -n --arg text "$PROMPT" '{
            contents: [ { parts: [ { text: $text } ] } ]
          }')

          RESPONSE=$(curl -s "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=$GEMINI_API" \
            -H "Content-Type: application/json" \
            -X POST \
            -d "$PAYLOAD")

          SUMMARY=$(echo "$RESPONSE" | jq -r '.candidates[0].content.parts[0].text')
          echo "Résumé météo : $SUMMARY"

          {
            echo "SUMMARY<<EOF"
            echo "$SUMMARY"
            echo "EOF"
          } >> "$GITHUB_ENV"

      - name: Generate voice with Coqui TTS (MP3)
        env:
          SUMMARY: ${{ env.SUMMARY }}
        run: |
          set -e
          echo "$SUMMARY" > summary.txt

          # Generate WAV
          TTS --text "$SUMMARY" \
              --model_name "tts_models/fr/mai/tacotron2-DDC" \
              --out_path weather.wav

          # Convert WAV to MP3
          ffmpeg -y -i weather.wav weather.mp3

      - name: Upload MP3
        uses: actions/upload-artifact@v4
        with:
          name: weather-audio
          path: weather.mp3
