name: Hello Action
on:
  push:
    branches:
      - main
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/hello-action@1.0.0
        with:
          name: Martin
                    
