name: Hello Action 2
on:
  push:
    branches:
      - main
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: VipInformatique/hello-action@1.0.1
        with:
          name: Martin
                    
