# Nom du workflow
name: Talk Weather

# Déclenchement du workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "*/2 * * * *"  # Chaque 2 minutes

jobs:
  ask-weatherr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Afficher l’heure d’exécution
        run: date

      - name: Get temperature only
        run: |
          TEMP=$(curl -s https://wttr.in/Paris)
          echo "Température brute:"
          echo "$TEMP"


        
       
             #   curl "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=${{ secrets.GEMINI_API }}" \
  #    -H 'Content-Type: application/json' \
  #    -X POST \
 #     -d '{
  #      "contents": [{
  #        "parts":[{"text": Quel temps fait-il à Paris en ce moment ?"$TEMP"}]
   #       }]
   #     }'


      - name: Convertir en parole avec ElevenLabs
        env:
          ELEVENLABS_API_KEY: ${{ secrets.ELEVENLABS_API_KEY }}
          TEXT: ${{ env.TEXT }}
        run: |
          echo "Texte à lire : $TEXT"

          # VOICE_ID francophone (ex : "Chloé")
          VOICE_ID="AZnzlk1XvdvUeBnXmlld" 
          
          curl -X POST https://api.elevenlabs.io/v1/text-to-speech/$VOICE_ID \
            -H "xi-api-key: $ELEVENLABS_API_KEY" \
            -H "Content-Type: application/json" \
            -d "{
              \"text\": \"$TEXT\",
              \"model_id\": \"eleven_multilingual_v1\",
              \"voice_settings\": {
                \"stability\": 0.5,
                \"similarity_boost\": 0.75
              }
            }" --output weather.mp3

      - name: Télécharger l’audio
        uses: actions/upload-artifact@v4
        with:
          name: voix-meteo
          path: weather.mp3
