# Nom du workflow
name: Talk Weather

#Déclenchement du workflow
on:
  push:
    branches:
      - main 
  # cliquer sur le bouton
  workflow_dispatch:

  schedule:
    # Chaques 2 minutes
    - cron: "*/2 * * * *"

jobs: 
  # Nom du job
  ask-weatherr:
    # Nom de l'agent
    runs-on: ubuntu-latest
    # Les étapes du job
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get Weather
        run: 
          curl wttr.in/Paris

