- name: Get weather data and generate response
  id: ask_gemini
  run: |
    TEMP=$(curl -s https://wttr.in/Paris)
    PROMPT="Résume la météo à Paris à partir de la réponse suivante : $TEMP"

    RESPONSE=$(curl -s "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=${{ secrets.GEMINI_API }}" \
      -H 'Content-Type: application/json' \
      -X POST \
      -d "$(jq -n --arg text "$PROMPT" '{contents: [{parts: [{text: $text}]}]}')"
    )

    echo "RAW RESPONSE:"
    echo "$RESPONSE"

    # Wyciągnięcie tekstu odpowiedzi z JSON
    TEXT=$(echo "$RESPONSE" | jq -r '.candidates[0].content.parts[0].text')

    echo "Réponse générée par Gemini :"
    echo "$TEXT"
