name: Talk Weather

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "*/2 * * * *"  # Każde 2 minuty

jobs:
  ask-weather:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Afficher l’heure d’exécution
        run: date

      - name: Get weather data
        id: get_weather
        run: |
          TEMP=$(curl -s https://wttr.in/Paris)
          reponse=$(curl "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=${{ secrets.GEMINI_API }}" \
          -H 'Content-Type: application/json' \
          -X POST \
          -d '{
          "contents": [{
          "parts":[{"text": "Explain how AI works"}]
          }]
          }')

          echo "$reponse"